libname hw8 "C:\Users\riverboy\Box\share\catagory hw8";
data hw8;
set hw8.child_ill;
data new;
set hw8;
IF NUM_ILL = 0 THEN y = 0;
ELSE IF 0 < NUM_ILL <= 2 THEN y = 1;
ELSE IF NUM_ILL >3 THEN y = 2;
RUN;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw8\a.rtf';
PROC LOGISTIC DATA=new DESCENDING;
CLASS GENDER / PARAM=REF;
MODEL y = GENDER / LINK=GLOGIT;
RUN;
ods rtf close;
proc logistic data=new descending;
class gender(ref=first)/param=ref;
Model y=GENDER/link=glogit scale=none aggregate=(gender);
run;
