libname hw7 "C:\Users\riverboy\Box\share\catagory hw7";
data dos;
set hw7.dos;
data dos1;
set dos;
if dep>0 then depd = 1;
else if dep = 0 then depd = 0;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw7\depression_probit.rtf';
PROC LOGISTIC DATA=dos1 DESCENDING;
MODEL depd(ref = '1') = Age / LINK = probIT LACKFIT;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw7\nodepression_probit.rtf';
PROC LOGISTIC DATA=dos1 DESCENDING;
MODEL depd(ref = '0') = Age / LINK = probIT LACKFIT;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw7\depression_loglog.rtf';
PROC LOGISTIC DATA=dos1 DESCENDING;
MODEL depd(ref = '1') = Age / LINK = cloglog LACKFIT;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw7\nodepression_loglog.rtf';
PROC LOGISTIC DATA=dos1 DESCENDING;
MODEL depd(ref = '0') = Age / LINK = cloglog LACKFIT;
RUN;
ods rtf close;
data heart;
set hw7.heart;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw7\q2_logit.rtf';
PROC LOGISTIC DATA=heart;
	class anterior kk1 kk2 kk3 kk4 age1 age2 age3 age4;
    MODEL death = anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 / LINK=LOGIT LACKFIT;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw7\q2_probit.rtf';
PROC LOGISTIC DATA=heart;
	class anterior kk1 kk2 kk3 kk4 age1 age2 age3 age4;
    MODEL death(event='1') = anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 / LINK=probit LACKFIT;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw7\q2_cloglog1.rtf';
PROC LOGISTIC DATA=heart ;
	class anterior kk1 kk2 kk3 kk4 age1 age2 age3 age4;
    MODEL death(event='1') = anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 / LINK=cloglog LACKFIT;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw7\q2_cloglog2.rtf';
PROC LOGISTIC DATA=heart;
	class anterior kk1 kk2 kk3 kk4 age1 age2 age3 age4;
    MODEL death(event='0') = anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 / LINK=cloglog LACKFIT;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw7\q2_cloglog2.rtf';
PROC LOGISTIC DATA=heart;
	class anterior kk1 kk2 kk3 kk4 age1 age2 age3 age4;
    MODEL death = anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 / LINK=identity LACKFIT;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw7\q2_identity.rtf';
PROC genmod DATA=heart descending;
	class anterior(ref=first) hcabg(ref=first)/param = ref;
    MODEL death = anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 /d=binomial LINK=identity;
	output out=h pred=p;
RUN;
proc rank data=h out=h2 groups=11;
	var p;
	ranks prank;
run;
proc freq data=h2;
table prank;
run;
ods rtf close;






ods rtf file='C:\Users\riverboy\Box\share\hw7\q2_logit.rtf';
PROC genmod DATA=heart descending;
	class anterior kk1 kk2 kk3 kk4 age1 age2 age3 age4;
    MODEL death = anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 /d=binomial LINK=logit;
	output out=logit predicted=ProbDeath_logit;
RUN;
proc corr data=logit out=corr_matrix_logit;
run;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\hw7\q2_probit.rtf';
PROC genmod DATA=heart descending;
	class anterior kk1 kk2 kk3 kk4 age1 age2 age3 age4;
    MODEL death = anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 /d=binomial LINK=probit;
	output out=probit predicted=ProbDeath_probit;
RUN;
proc corr data=probit out=corr_matrix_probit;
run;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\hw7\q2_cloglog1.rtf';
PROC genmod DATA=heart descending;
	class anterior kk1 kk2 kk3 kk4 age1 age2 age3 age4;
    MODEL death(event='1')= anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 /d=binomial LINK=cloglog;
	output out=cloglog1 predicted=ProbDeath_cloglog1;
RUN;
proc corr data=cloglog1 out=corr_matrix_cloglog1;
run;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\hw7\q2_cloglog2.rtf';
PROC genmod DATA=heart descending;
	class anterior kk1 kk2 kk3 kk4 age1 age2 age3 age4;
    MODEL death(event='0')= anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 /d=binomial LINK=cloglog;
	output out=cloglog2 predicted=ProbDeath_cloglog2;
RUN;
proc corr data=cloglog2 out=corr_matrix_cloglog2;
run;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\hw7\q2_identity.rtf';
PROC genmod DATA=heart descending;
	class anterior kk1 kk2 kk3 kk4 age1 age2 age3 age4;
    MODEL death = anterior hcabg kk1 kk2 kk3 kk4 age1 age2 age3 age4 /d=binomial LINK=identity;
	output out=identity predicted=ProbDeath_identity;
RUN;
proc corr data=identity out=corr_matrix_identity;
run;
ods rtf close;


