libname hw9 "C:\Users\riverboy\Box\share\catagory hw8";
data hw9;
set hw9.child_ill;
data new;
set hw9;
IF NUM_ILL = 0 THEN y = 0;
ELSE IF 0 < NUM_ILL <= 2 THEN y = 1;
ELSE IF NUM_ILL >=3 THEN y = 2;
RUN;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw9\a.rtf';
PROC LOGISTIC DATA=new DESCENDING;
CLASS GENDER / PARAM=REF;
MODEL y = GENDER / LINK=cLOGIT;
contrast "GENDER 1 vs 3" GENDER 1;
contrast "GENDER 2 vs 3" GENDER 0 1; 
contrast "GENDER 1 vs 2" GENDER 1 -1; 
contrast "GENDER" GENDER 1 , GENDER 0 1; 
estimate "GENDER 1" intercept 1 GENDER 1; 
estimate "GENDER 1" intercept 1 GENDER 1/CATEGORY='1';RUN; 
PROC LOGISTIC DATA=new DESCENDING; CLASS GENDER / PARAM=REF;
MODEL y = GENDER / LINK=cLOGIT unequalslopes;
contrast "GENDER 1 vs 3" GENDER 1;
contrast "GENDER 2 vs 3" GENDER 0 1; 
contrast "GENDER 1 vs 2" GENDER 1 -1; 
contrast "GENDER" GENDER 1 , GENDER 0 1; 
estimate "GENDER 1" intercept 1 GENDER 1; 
estimate "GENDER 1" intercept 1 GENDER 1/CATEGORY='1';RUN; 
ods rtf close;

PROC CONTENTS DATA=CDA9;
RUN;
DATA CDAHW9;
SET CDA9;
IF NUM_ILL=0 THEN Y=0;
IF 1<=NUM_ILL<=2 THEN Y=1;
IF NUM_ILL>=3 THEN Y=2;
IF GENDER='F' THEN G=1;
ELSE IF GENDER='M' THEN G=0;
RUN;
PROC CONTENTS DATA=CDAHW9;
RUN;
PROC LOGISTIC DATA=new DESCENDING;
CLASS GENDER / PARAM=REF;
MODEL y = GENDER / LINK=cLOGIT;
proc genmod data=new;
  class gender;
  model y = gender / dist=bin link=logit;
  repeated subject=idvar / within=threshold_var type=cr;
run;
DATA new1;
set new;
stage=1; event = (y eq 0); output; if y eq 0 then delete;
stage=2; event = (y eq 1); output; if y eq 1 then delete;
stage=3; event = (y eq 2); output;
run;
PROC LOGISTIC DATA=new1 DESCENDING;
CLASS GENDER / PARAM=REF;
MODEL y = GENDER / LINK=cLOGIT;
proc logistic data=new1 order=internal desc;
  class GENDER / PARAM=REF;
  model event=stage gender / aggregate scale=none expb;
run;

proc logistic data=new1 order=internal desc;
  class GENDER / PARAM=REF;
  model event=stage gender / aggregate scale=none expb;
run;

proc print data=new1(obs=25);
run;
proc logistic data=new1;
  class GENDER / PARAM=REF;
  model Y= GENDER/link=alogit lackfit scale=none aggregate=(G) UNEqualslopes=G;
  test G1=G1_0=0;
run;
proc logistics data=new1;
  class GENDER / PARAM=REF;
  MODEL Y= GENDER/link=alogit;
run;
