libname hw11 'C:\Users\riverboy\Box\share\catagory hw11';
data hw11;
set hw11.dos;
run;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw11\1a.rtf';
proc genmod data=hw11;
class dep gender;
model Count = dep|gender / dist=poisson link= log type3;
run;
proc freq data=hw11;
tables dep*gender / chisq;
run;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw11\2bc.rtf';
data hw11;
set hw11;
row=Marital;col=dep;
run;
proc genmod data=hw11;
class row col;
model Cirsttl= row col dep|Marital/d=Poisson link=log;
run;
proc genmod data=hw11;
class row col/param=glm;
model Cirsttl= row col dep|Marital/d=Poisson link=log wald noint;
run;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw11\3a.rtf';
PROC GENMOD DATA=hw11;
CLASS GENDER Marital DEP;
MODEL Cirsttl = Gender Marital dep
/ LINK=LOG DIST=POISSON TYPE3;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw11\3a.rtf';
PROC GENMOD DATA=hw11;
CLASS GENDER Marital DEP / PARAM=EFFECT;
MODEL Cirsttl = Marital |DEP | gender / LINK=LOG
DIST=POISSON TYPE3;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw11\3b.rtf';
PROC GENMOD DATA=hw11;
CLASS GENDER Marital DEP ;
MODEL Cirsttl = DEP GENDER Marital GENDER*Marital
/ LINK=LOG DIST=POISSON TYPE3;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw11\3c.rtf';
PROC GENMOD DATA=hw11;
CLASS GENDER Marital DEP ;
MODEL Cirsttl = DEP GENDER Marital GENDER*Marital
/ LINK=LOG DIST=POISSON TYPE3;
RUN;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw11\3b.rtf';
proc freq data=hw11;
table gender*Marital*DEP/cmh;
run;
PROC GENMOD DATA=hw11;
CLASS GENDER Marital DEP ;
MODEL Cirsttl = GENDER Marital DEP GENDER*Marital Marital*DEP/LINK=LOG DIST=POISSON;
RUN;
proc freq data=hw11;
table Marital*gender*dep/cmh;run;
ods rtf close;
ods rtf file='C:\Users\riverboy\Box\share\catagory hw11\5.rtf';
data ppd;
set hw11.ppd;
run;
proc genmod data=ppd;
class Cmajmin EPDS group;
model bdi = Cmajmin EPDS group Cmajmin*EPDS group*EPDS group*Cmajmin / dist=poisson link=log TYPE3;
run;
proc freq data=ppd;
    tables group*Cmajmin*EPDS / expected;
run;
proc genmod data=ppd;
    class group Cmajmin EPDS;
    model bdi = group|Cmajmin|EPDS / link=log dist=poisson type3;
run;
ods rtf close;
